[FIX/#122] 모임 생성, 가입 에러 핸들
OMZigak/KKUM_ANDROID pull request #123
Opened 2024-08-06 03:11 UTC by yskim6772

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #122

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ] 모임 생성 에러 핸들링
- [ ] 모임 가입 에러 핸들링
- [ ] 모임 상세화면 다이얼로그 오류 해결

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/4416d226-7f78-43d3-ad42-d2e99dc3c460

https://github.com/user-attachments/assets/475a3003-3dca-4f85-aa69-ef1f9c7c3d52

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀

2024-08-06 07:55 UTC, chanubc requested changes
잘하셧습니다1!

2024-08-06 07:55 UTC, chanubc commented on feature/src/main/AndroidManifest.xml
> +            android:windowSoftInputMode="adjustResize" />
p3: MainActivity를 adustresize적용하게 되면 이에따른 부작용은 없을까요?
adjust resize가 필요하지 않은 화면의 경우에서요!

2024-08-06 07:55 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +                    bundleOf("code" to code, "sourceFragment" to "myGroupDetail"),
p1 : code도 상수화 해주세요!
"sourceFragment" to "myGroupDetail" 이건 뭐죠?
key도 상수화 해주세요!
value로 어디서 오는지 파악하는 것 같은데 이것도 key값으로 봐야할 것 같아서 변수나 상수로 따로 할당하는게 나을것 같습니다.

2024-08-06 07:55 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
> +        requireArguments().getString(SOURCE_FRAGMENT, "")
p1 : requireArguments()는 반드시 값을 가지고 오는 로직이라 약간은 위험할수있습니다!
arguments로 바꿔주세요!

2024-08-06 07:55 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
> +                "addNewGroup" -> {
p1 : 상수화 해주세요!

2024-08-06 07:55 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
>                  }
p1 : 이전화면에서 jetpack navi를 통해서 이동하고 값을 전달하는식이라 newInstance필요 없지 않나요?
한번 확인해주시겠어요?

2024-08-06 08:19 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
>                  }
넵 확인해보니 불필요한 부분이었습니다! 수정하겠습니다!

2024-08-06 08:55 UTC, yskim6772 commented on feature/src/main/AndroidManifest.xml
> +            android:windowSoftInputMode="adjustResize" />
수정해본 결과 activity에서 적용하지 않고 특정 fragment의 onCreate에서 바로 adjustresize를 적용하려 하면 적용이 되지 않았습니다..!
그리고 adjustresize가 필요한데 fragment나 activity 코드에서 적용하려 하니 deprecated 경고가 뜹니다..!
현재는 저게 최선 방법처럼 보이는데 나중에 좀 더 고민해보겠습니다 !!

2024-08-06 09:24 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
> +        private const val CODE = "code"
p1 : 해당 화면 외부에서도 사용되는 key값들은 keyStorage
내부에서만 사용되면 compnaion object에 배치시켜주세요!

2024-08-06 09:37 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/newgroup/addnewgroup/DialogInvitationCodeFragment.kt
> +        private const val CODE = "code"
넵 ! 반영하였습니다 !

2024-08-06 09:44 UTC, chanubc approved these changes
goooD! 머지 하셔도 좋습니다

2024-08-09 04:31 UTC, yskim6772 commented
지각꾸물이 뷰 확장함수 적용 및 분기처리 수정 완료했습니다 
확인 한번 해주시면 머지하겠습니다 !

2024-08-09 05:54 UTC, chanubc approved these changes
이제는 문제없이 돌아가죠?
build해보고 이상 없으면 머지해주세요~

2024-08-09 05:54 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonFragment.kt
> +        }
goood! 확장함수의 장점을 알겠죠??

2024-08-09 05:54 UTC, chanubc commented on feature/src/main/res/layout/fragment_late_person.xml
> +
좋아요!!

2024-08-09 14:44 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/meetup/lateperson/LatePersonFragment.kt
> +        }
완전요 .. 앞으로 잘 활용해보겠습니다-! 😊

2024-08-09 14:45 UTC, merged