[Feat/#129] sprint my group detail
OMZigak/KKUM_ANDROID pull request #130
Opened 2024-08-18 08:39 UTC by hyoeunjoo

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ] toolbar에 (...) 아이콘 추가 
- [ ] 각 화면에서 (...) 아이콘 visible, invisible처리
- [ ] 모임 상세 화면에서 (...) 누를 시 바텀시트에 모임명 뜨게 서버에서 받아오기
- [ ] 내가 속한 약속, 모든 약속 텍스트 누를 때 값 처리

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/c60a1a8c-ce8f-4a7c-b3a2-a478a428819f

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀

2024-08-18 08:57 UTC, chanubc requested changes
고생많으셨습니다!
리뷰 확인해주세요

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        binding.vAllMeetUp.visibility = if (isVisible) View.GONE else View.VISIBLE
p1 : setVisible 확장함수 사용해주세요!

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        binding.tvAllMeetUp.setTextColor(ContextCompat.getColor(requireContext(), R.color.gray6))
p1 : 마찬가지로 colorOf 확장함수 사용해주세요

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        }
p1 : initView블록안에는 함수분리 해주세요

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +    }
이거 xml에서 선언해도 되지 않나요?

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/res/layout/fragment_exit_bottom_sheet.xml
> +        android:layout_height="match_parent">
p1  : 여기 background에 bottom sheet에 대한 drawable이 필요합니다. 지금은 radius적용이 안되있어요

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/res/layout/fragment_exit_bottom_sheet.xml
> +        android:layout_height="match_parent">
또 height은 wrap으로 해주세요

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/res/layout/fragment_my_group_detail.xml
> +                android:text="내가 속한 약속"
p1 : text추출 해주세요!

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/res/navigation/nav_graph.xml
> +
p3 : 불필요한 개행은 지워주세요! 저희는 ktlint plugin 사용하기에 ctrl+atl+l 누르면 지워질겁니다

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/res/layout/view_toolbar.xml
> +                android:src="@drawable/ic_btn_more_36" />
p1 : 이거 visibiity gone이나 invisible적용하고 사용하는데서만 visible처리 해주세요!

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
> +        binding.tbMeetUpCreate.ivBtnMore.visibility = View.GONE
p1 : 이거 삭제하고 필요한 부분에서 visible처리로 바꿔주세요
toolbar는 공통이기때문에 모든 레이아웃에서 gone처리 해야 할거에요

2024-08-18 08:57 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
> +        binding.tbMeetUpCreate.ivBtnMore.visibility = View.GONE
아래 xml에 코멘트 달아 놓았습니다

2024-08-18 10:37 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        binding.vAllMeetUp.visibility = if (isVisible) View.GONE else View.VISIBLE
아맞네용

2024-08-18 10:42 UTC, hyoeunjoo commented on feature/src/main/res/layout/fragment_exit_bottom_sheet.xml
> +        android:layout_height="match_parent">
헉 만들어놨는데 적용하는 것을 깜빡했네요 감사합니다

2024-08-18 11:17 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +    }
맞습니다....

2024-08-18 12:28 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/meetuplevel/MeetUpLevelFragment.kt
> +        binding.tbMeetUpCreate.ivBtnMore.visibility = View.GONE
훨씬 간단한 방법인 것 같습니다

2024-08-18 12:46 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +    }
엇 이건 그냥 물어본거라 바꿀필욘 없습니다! 근데 아마 xml에 백그라운드 설정하고 펼쳐지는 특별한 애니메이션이 없다면 저 부분 필요 없을거에요.

2024-08-18 12:47 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> -    }
엇 지우란는 뜻은 아니였는데.. 하지만 없어도 잘 돌아 갈겁니다

2024-08-18 12:47 UTC, chanubc commented on feature/src/main/res/layout/fragment_exit_bottom_sheet.xml
> +            app:layout_constraintHorizontal_bias="0.0"
p1 : 이것도 지워주세요!

2024-08-18 13:00 UTC, chanubc reviewed
고생하셨어요
불필요한 이미지있는지 한번 확인해주세요!

2024-08-18 13:00 UTC, chanubc commented on feature/src/main/res/values/themes.xml
> +    </style>
p2 : background dim 바텀시트에서도 없애는지 한번 디자인에 문의해 보시겠나요?

2024-08-18 13:09 UTC, hyoeunjoo commented on feature/src/main/res/layout/fragment_exit_bottom_sheet.xml
> +            app:layout_constraintStart_toStartOf="parent" />
![image](https://github.com/user-attachments/assets/da7929aa-2813-4483-a724-92e5c08b3a88)

이거 뒤에 회색 배경입니다

2024-08-18 13:09 UTC, hyoeunjoo commented on feature/src/main/res/values/themes.xml
> +    </style>
넵 문의했습니당

2024-08-18 13:19 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> -    }
아 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 맞습니다 없어도 잘 돌아갑니다..^^..

2024-08-18 13:19 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> -    }
ㅋㅋㅋㅋㅋㅋㅋ앗 ㅋㅋㅋ 맞습니다.. 없어도 잘 돌아가네여...^^...

2024-08-18 13:28 UTC, chanubc requested changes
p1사항 확인해주세요

2024-08-18 13:28 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +        val id = arguments?.getInt(KeyStorage.MEETING_ID) ?: -1
```suggestion
    private val currentId: Int by lazy { arguments?.getInt(KeyStorage.MEETING_ID, -1) }

    override fun initView() {
     if (currentId != -1) {
            viewModel.getMyGroupInfo(currentId)
        }
```
이렇게 by lazy활용하는 법도 있을 것 같아요

2024-08-18 13:28 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +    private val viewModel: MyGroupDetailViewModel by viewModels()
p1 : 실질적인 나가기는 alert dailog fragment에서 해야해서 관련 코드는 지워주세요! 아래 stata observing이랑 viewmodel 쓰는것도 필요 없어보여요.
오히려 다음 dailog fragment로 해당 id를 넘기는 로직이 필요 할 것 같아요

2024-08-18 13:28 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +        binding.tvGroupName.text = myGroupInfoModel.name
p1 : 이건 왜 필요하죠?

2024-08-18 13:28 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +    }
p1 : 전혀 필요 없는 로직 같습니다! 넣으신 이유가 있나요?

2024-08-18 13:28 UTC, chanubc commented on feature/src/main/res/layout/fragment_exit_bottom_sheet.xml
> +            app:layout_constraintStart_toStartOf="parent" />
p1 : 회색 배경이면 textview의 background및 backgroundTint를 지정하시면 됩니다

2024-08-18 13:28 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +        }
p1 : 만약에 여기서 서버 통신을 해서 옵저빙을 한다해도 dismiss하는 취소 버튼은 서버 통신이 성공하든 실패하든 항상 눌려야 합니다. 지금 로직은 이상한 것 같습니다.

2024-08-18 13:28 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +        }
물론 여기서 서버 통신을 해서 받아올 것 도 없구요

2024-08-18 16:25 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/utils/BottomSheetExitFragment.kt
> +    private val viewModel: MyGroupDetailViewModel by viewModels()
네 알겠습니다 모임명을 띄우기 위해서 서버통신을 해야겠다고 생각했는데 남겨주신대로 모임명 하나 받아오겠다고 서버통신하는 건 아닌 것 같습니다. 말씀하신대로 meetingId와 모임명만 Bundle로 넘겨보겠습니다

2024-08-22 02:18 UTC, chanubc approved these changes
goood! 좋습니다

2024-08-22 06:25 UTC, merged