[Feat/#137] meet up edit
OMZigak/KKUM_ANDROID pull request #138
Opened 2024-08-22 12:34 UTC by hyoeunjoo

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ]  모임 상세페이지 
- [ ] 

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀

2024-08-22 15:10 UTC, chanubc requested changes
p1사항들만 확인해 주세요!

2024-08-22 15:10 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt
> +
p3 : 여기 emptyview있지 않나요? 없나 이제?

2024-08-22 15:10 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt
> +                    }
p1 : empty뷰도 viewmodel에서 emit해주세요 아래 Mygroup에서 하신 방식대로요!

2024-08-22 15:10 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        viewModel.getMyGroupMeetUp(currentId, false, false)
p1 : 이거 일단 true로 해놓고 추후 서버 통신할때 true false 함수 2개부르면 됩니다

2024-08-22 15:10 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailViewModel.kt
> +                    }
goood!!

2024-08-22 15:10 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/adapter/MyGroupDetailMeetUpAdapter.kt
> +            onItemsTheSame = { old, new -> old.promiseId == new.promiseId },
good!!

2024-08-22 15:10 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/time/formatTimeToPmAm.kt
> +        return outputDateFormatText.format(date)
오 잘만드셨네요

2024-08-22 16:15 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        viewModel.getMyGroupMeetUp(currentId, false, false)
넵!! ㅎㅎ 찾아주셔서 감사합니다

2024-08-22 16:27 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/utils/time/formatTimeToPmAm.kt
> +        return outputDateFormatText.format(date)
틀을 잘 만들어주셔서 따라했을뿐입니다 ㅎㅅㅎ

2024-08-22 16:51 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt
> +
empty view 있습니다! 다시 바꿔놓겠습니다.

2024-08-23 05:14 UTC, chanubc approved these changes
ui까지 잘나오네요! 서버 통신한번해보세요~

2024-08-23 05:14 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/MeetUpCreateViewModel.kt
> +                }
good! 좋습니다

2024-08-23 05:51 UTC, yskim6772 approved these changes
수고하셨습니다-! 😉

2024-08-23 05:51 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/meetupcreate/friend/MeetUpCreateFriendFragment.kt
> +    }
empty view 처리 깔끔하네요 ~

2024-08-23 05:51 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/utils/time/formatTimeToPmAm.kt
> +        return outputDateFormatText.format(date)
최고 👍🏻

2024-08-23 08:35 UTC, merged