[Feat/#139] 모임 상세 페이지 서버통신 구현
OMZigak/KKUM_ANDROID pull request #140
Opened 2024-08-23 23:56 UTC by hyoeunjoo

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ] 모임 상세페이지에서 모임 나가기 -> 내 모임 목록으로 이동
- [ ] 모임 내 약속에서 내가 포함된 목록/모든 목록 누른 것에 따라 다른 약속 받아오기

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/c6d72210-149b-4e0f-8bbc-b71128d3a452

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀

2024-08-24 01:14 UTC, chanubc requested changes
고생하셨습니다!
잘하셨네용

2024-08-24 01:14 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogViewModel.kt
> +      }*/
p1 : 불필요한 주석은 제거햊수세요!

2024-08-24 01:14 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogViewModel.kt
> +    private val _deleteMyGroupState = MutableStateFlow<UiState<Unit>>(UiState.Loading)
p1 : 
```suggestion
    private val _deleteMyGroupState = MutableSharedFlow<UiState<Unit>>(UiState.Loading)
```

2024-08-24 01:14 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
> +                )
p2  : 여기서 colorOf 확장함수 사용 불가 인가요?

2024-08-24 01:14 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
> +                is UiState.Failure -> Timber.tag("delete my group").d(uiState.errorMessage)
p1 : 삭제 실패시 서버에서 제공하는 메세지를 toast로 띄워주세요!

2024-08-24 01:14 UTC, chanubc commented on core/network/src/main/java/com/teamkkumul/core/network/api/MyGroupService.kt
> +        @Query("isParticipant") isParticipant: Boolean?,
p1 : 왜 null허용으로 바꾸셨나요? true false 둘다 넣는게 나을 것 같아요!
불필요한 null은 프로그래밍시 좋지는 않아요!

2024-08-24 01:14 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        viewModel.getMyGroupMeetUp(currentId, false)
여기서 false를 넣어도 되지 않을까요?
그게 더 명시적일것 같아요

2024-08-25 13:06 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogViewModel.kt
> +    private val _deleteMyGroupState = MutableStateFlow<UiState<Unit>>(UiState.Loading)
헉 이거 테스트해보고 바꾼다는 걸.... 감사합니다!!

2024-08-25 13:21 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/utils/dialog/DeleteDialogFragment.kt
> +                )
앗 가능합니다! 제가 쓴 부분이 아니라 줄정리만 하고 확인을 못했는데 다음부터는 전체적인 코드들 하나씩 보면서 바꿀 수 있는 부분들은 바꾸겠습니다!

2024-08-25 13:49 UTC, hyoeunjoo commented on core/network/src/main/java/com/teamkkumul/core/network/api/MyGroupService.kt
> +        @Query("isParticipant") isParticipant: Boolean?,
앗 이걸 이렇게 한 이유는 서버 api명세서를 보았을 때 query parameter에 넣은 값을 기준으로 내 약속인지(true)아닌지(false) 필터링을 하기 때문입니다. 

해당 파라미터 값이 필수가 아니고, 오히려 파라미터 값을 주지 않아야만 해당 모임의 모든 약속 목록을 반환하기 때문에 null허용으로 만들었습니다!

false로 할 시, 모든 약속 목록이 반환되지 않고 내가 속하지 않은 약속만이 반환됩니다!

2024-08-25 15:00 UTC, chanubc approved these changes
여기 하나만 수정해주세요!

2024-08-25 15:04 UTC, chanubc commented on core/network/src/main/java/com/teamkkumul/core/network/api/MyGroupService.kt
> +        @Query("isParticipant") isParticipant: Boolean?,
파라미터 값을 주지 않으면 자동으로 false로 들어가게끔 설계되어 있습니다

![image](https://github.com/user-attachments/assets/e19ce192-f81f-4116-a2f0-7e7a0e99ce37)


done도 false를 주면 모든 리스트를 반환합니다

2024-08-25 15:06 UTC, merged