[FEAT/#141] 약속 나가기, 삭제하기 서버 통신
OMZigak/KKUM_ANDROID pull request #148
Opened 2024-08-26 09:41 UTC by yskim6772

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #141

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ] 약속 상세 다이얼로그 연결
- [ ] 약속 나가기 서버 통신
- [ ] 약속 삭제하기 서버 통신
- [ ] 약속 상세 약속 이름 받아오기
- [ ] 지각꾸물이 뷰 sharedflow 적용
- [ ] 내가 속하지 않은 약속 ui 수정 (더보기 버튼 X)
- [ ] 약속 상세 디데이 ui 수정 - 약속 상세 response dto에 dday가 없어서 아직 고민입니다 ,, mygroupdetail의 recyclerview에서 받아올지 아님 time으로 계산(?)해야할지..?

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/6f69c9d6-32df-4a21-ad88-38ae72202103

https://github.com/user-attachments/assets/37b43d82-75fa-4769-9d1a-75ea25094dc1

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
약속 나가기, 약속 삭제 다이얼로그 연결 및 서버 통신 구현했습니다. 
지각꾸물이 뷰 mutablesharedflow 적용하였고, 
약속 상세에서 디데이를 받아와야 하는데, (디데이 따라 전체 흑백처리 되는 것도 적용해야 합니다)
약속 상세 response dto에 dday가 없어서 아직 고민중이었습니다..!

2024-08-26 09:51 UTC, chanubc approved these changes
자랗셨습니다!!

앞선 리사이클러뷰에서 해당 d-day에 해당하는 time을 넘겨줘야 할 것 같네요ㅠ

2024-08-26 09:51 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetup/MeetUpContainerFragment.kt
> +            if (meetUpDetailModel.isParticipant == true) View.VISIBLE else View.INVISIBLE
p23 : invisbile 도 setvisible처럼 확장함수 만들어 보실래요?

2024-08-26 10:03 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/meetup/MeetUpContainerFragment.kt
> +            if (meetUpDetailModel.isParticipant == true) View.VISIBLE else View.INVISIBLE
넵 확장함수 만들어보겠습니다 ! 약속 상세에서 받은 time 파싱해서 d-day 계산도 해보겠습니다-! 감사합니다 😄

2024-08-26 14:59 UTC, chanubc requested changes
p1 : 확장함수 만드는 법 터득하셨네요!
잘하셨습니다 코드리뷰 확인해주세요

2024-08-26 14:59 UTC, chanubc commented on core/network/src/main/java/com/teamkkumul/core/network/dto/request/RequestMeetUpCreateDto.kt
> +    val y: Double? = null,
p1  : 이거 서버와 협의 된건가요?

2024-08-26 14:59 UTC, chanubc commented on core/ui/src/main/java/com/teamkkumul/core/ui/view/ViewTextColorExt.kt
> +        setTextColor(colorResId)
p1 : 해당 exception은 resource를 찾을 수 없을 때 나오는 예외입니다. resource를 못찾았는데 함수에 또 넣는거는 계속 예외를 야기시키겠죠

R.color에 있는 resource를 직접 넣는것이 낫습니다

그리고 이러한 resId를 활용해야 하는 확장함수라면 feature에 존재하는게 맞습니다. 현재 ui모듈에는 res에 대한 의존성이 없어요

2024-08-26 14:59 UTC, chanubc commented on core/ui/src/main/java/com/teamkkumul/core/ui/view/ViewTextColorExt.kt
> +fun TextView.setTextColorRes(colorResId: Int) {
```suggestion
fun TextView.setTextColorRes(@ColorRes colorResId: Int) {
```

2024-08-26 14:59 UTC, chanubc commented on core/ui/src/main/java/com/teamkkumul/core/ui/view/ViewTextColorExt.kt
> +        (rootView.findViewById<View>(id) as? TextView)?.setTextColorRes(colorResId)
p1 : findViewById에서 아시나요? 1주차 세미나 자료를 확인하시면 좋습니다.
특히 findviewByid의 경우 동적으로 루트에서 시작하여 트리구조를 통해 해당하는 뷰까지 타고타고 내려가는 식이기 때문에 매번 처음부터 끝까지 탐색을 해야합니다. 뷰가 중첩되거나 깊이가 깊은경우 매우 비효율적입니다.
여기서는 for문을 써서 반복적으로 부르기때문에 메모리, 성능적으로 좋은 로직은 아닙니다.

반대로 binding또한 중첩 구조에서는 이러한 점이 보완이 어렵지만 정적으로 미리 뷰 참조를 생성합니다.
따라서 컴파일 시에 이미 직접 뷰에 접근합니다. 따라서 동적 탐색 비용이 발생하지 않습니다

무엇보다 findviewbyid는 null안정성이 없기 런타임시에 오류를 발견 할 수 없고 컴파일 시에만 오류가 발견이 가능하기에 binding에 비해 비효율적입니다.

2024-08-26 14:59 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/time/timeUtil.kt
> +        }
p1 : 만들어 놓은 util함수 사용해주세요! 반복되는 코드는 보일러 플레이트를 유발합니다
```suggestion
        val dDayString =setDday(dDay)
```

2024-08-26 14:59 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/time/timeUtil.kt
> +        return Pair(dDayString, dDay)
p1 : dDay를 다시 return하는 이유가 있나요?

2024-08-26 14:59 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
> +            tvMeetUpDetailDday.setTextColor(context?.getColor(setDdayTextColor(dDayInt)) ?: R.color.gray3)
```suggestion
            tvMeetUpDetailDday.setTextColor(colorOf(setDdayTextColor(dDayInt)) ?: R.color.gray3)
```

2024-08-26 14:59 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/meetup/meetupdetail/MeetUpDetailFragment.kt
> +                groupMeetUpDetail.setTextColor(colorOf(R.color.main_color))
```kotlin
fun setDdayTextColor(dDay: Int): Int = when {
    dDay == 0 -> R.color.orange
    dDay > 0 -> R.color.gray3
    else -> R.color.gray5
}
```
이것도 나중에 제가 enum class로 분기처리해서 공통으로 묶겠습니다

2024-08-26 14:59 UTC, chanubc commented on feature/src/main/res/layout/fragment_meet_up_detail.xml
> +
오우 텍스트가 많네요

2024-08-26 16:53 UTC, merged

2024-08-28 12:07 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/utils/time/timeUtil.kt
> +        return Pair(dDayString, dDay)
위 함수가 time을 d-day로 파싱하는 함수여서, d-day int값과 d-day string값을 둘다 return해야 뷰에서 쓸 수 있다고 생각했었는데, setDday 확장함수를 쓰면서 int만 return하면 되는 걸로 해결했습니다 !