[REFACTOR/#154] 1차 스프린트 구현 수정, 리팩토링
OMZigak/KKUM_ANDROID pull request #156
Opened 2024-08-28 13:49 UTC by yskim6772

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #154

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ] 마이페이지 프로필 사진 수정 - onResume 구현 수정 -> register callback 사용
- [ ] #141 이슈 PR 코드리뷰 반영
- [ ] ViewTextColorExt 확장함수 수정 (약속 상세 text view 흑백처리 확장함수) - 새로 d-day 따라 color 및 image return 하는 함수 생성해서 해결 (SetMeetUpDetailColor.kt)
- [ ] 프로필 사진 수정, 약속 나가기 및 삭제하기 다이얼로그, 약속 상세 등 전반적 코드 리팩토링
- [ ] 지금은 넘어가기 버튼 안눌림 해결

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁
[마이페이지 프로필 수정 register call back + To Reviewers의 추가적 이슈]
https://github.com/user-attachments/assets/b96ba2c2-7c9f-443a-b3e0-d0aee0e7c540

[지금은 넘어가기 버튼 안눌림 해결]
https://github.com/user-attachments/assets/5d3bbd13-cb73-46cf-ba43-cff383233972

[약속 상세 화면 d-day 따라 ui 분기처리]
https://github.com/user-attachments/assets/a2ecefbc-da96-4464-af2e-5cc9c1e422f4

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
약속 상세 화면 PR 코드리뷰 반영 및 리팩토링, 
마이페이지의 프로필 사진 수정 구현 수정하였습니다. 
진행 내용 하단에 자세하게 적어놓았습니다 !

**[약속 상세 화면]**
textview 및 imageview가 d-day에 따라 달라야 하는 부분을, 
**SetMeetUpDetailColor.kt**에 

a. textview (5개)의 color를 d-day 따라 return하는 함수 (gray4 또는 main_color), 
b. 약속 이름 textview의 color를 d-day 따라 return하는 함수 (gray7 또는 gray4), 
c. imageview를 d-day 따라 return하는 함수

총 3개의 확장함수로 구현하였습니다.
이를 MeetUpDetailFragment에서 각 textview와 imageview당 한번씩 호출하여 사용하였습니다.

**[마이페이지의 프로필 사진 수정]**
MyPage -> SetProfile -> MyPage로 돌아왔을 때 MyPage의 imageview에 업데이트 된 사진이 반영되지 않는 문제를, 
MyPage의 setProfileLauncher라는 변수를 통해 **register call back** 방법을 사용하여 해결하였습니다. 

++ 추가적인 이슈 ..
MyPage에 돌아왔을 때는 잘 반영이 됩니다.
근데 여기서 다시 한번 MyPage의 이미지를 클릭하면, 
방금 업데이트된 사진으로 반영이 안됩니다 ...
그래서 또 register call back을 쓸까, 아님 mutable shared flow나 mutable state flow를 사용하는 방법을 모두 적용해봤는데 아직 해결책을 찾지 못한 상황입니다. 
(물론 MyPage 돌아왔을 때 다른 화면 한번만 갔다 오면, 이미지 클릭 시 그 이미지가 SetProfile에 잘 반영됨 ..)

방법 있으면 알려주시면 바로 반영해보겠습니다!

2024-08-28 15:09 UTC, chanubc requested changes
고생하셨습니다! 콜백쓴거 잘하셨네요!!

2024-08-28 15:09 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mypage/MyPageFragment.kt
> +
```kotlin
private lateinit var setProfileLauncher: ActivityResultLauncher<Intent>
```

binding을 사용하는 ui작업은 생명주기와 관련이 있습니다!
여기서는 액티비티이기 때문에 뷰의 생명주기와 액티비티의 생명주기가 동일해서 이렇게 사용해도 상관 없습니다!

다만 fragment에선 lateintit var로 선언하고

추후에 initView(OnViewCreated)블록안에서 해당 변수를 초기화 해주는것이 더 낫습니다!

2024-08-28 15:09 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/utils/color/SetMeetUpDetailColor.kt
> +}
p1 : dday를 파라미터로 받으니까 SetDay.kt 폴더 내부로 이동시켜주세요!

2024-08-28 15:09 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
> +                inputName?.let { navigateToWelcome(it) }
이러면 다음화면 넘어가지나요?
inputName이 null인경우도 있지 않나요? editText를 안눌렀을때 사용자가

2024-08-28 15:12 UTC, chanubc reviewed
지금 callback해서 받아온 url을 직접 ui붙이는데
callback이 성공하면 ==result ok
viewmodel의 get함수를 한번 더 호출하는 방법은 어떨까요?

2024-08-28 15:14 UTC, chanubc reviewed
그리고 위의 경우 callback의 ok여부로만 서버통신을 한번 더 시키는 거기 때문에 
앞선 화면에서 굳이 url보낼 필요는 없을것 같습니다!

2024-08-28 15:22 UTC, chanubc commented
![image](https://github.com/user-attachments/assets/fdf7404e-dcfb-4bd4-852b-5dc56139a82f)
이런식으로 성공했을때 서버 통신 한번 더하는 방안으로 하면 잘 됩니다!

2024-08-28 17:38 UTC, yskim6772 commented
헉 넵 위 사진과 설명해주신 것처럼 
callback에서 성공 시 뷰모델의 get 함수를 한번 더 호출하면 해결이 되네요 !!
뭔가 또 다시 넘겨주어야 한다는 생각 때문에 url 보내는 로직을 추가했던 것 같은데 그것도 불필요하고요

추가적으로 fragment에서는 callback을 쓸 때 val이 아닌 lateinit var로 선언하고 initView에서 초기화를 해주는 로직이 적합하다는 것도 알고 갑니다! 감사합니다 👍

2024-08-29 04:36 UTC, chanubc approved these changes
이미지 url넘기는 부분만 수정하시고 머지해주세요!

2024-08-29 04:36 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
> +        finish()
```kotlin
Intent().apply {
    putExtra(PROFILE_IMAGE_URL, selectedImageUri)
}.also {
    setResult(Activity.RESULT_OK, it)
    finish()
}
``` 
이제 오비가 되셨으니 scope에 대한 코드리뷰 받으실까봐 미리 작성드립닏다! 이런식으로 쓰는 법도 있습니다만
아마 이런 코드 리뷰 많이 받으실 겁니다.

불필요한 변수를 선언함으로써 메모리 절약 -> 이건 잘못 된 이야기 입니다.
val을 선언하나 IntentI()객체로 묶나 동일하게 메모리 할당되며, 다만 참조를 위한 이름이 있다 없다 차이 입니다.
 
추후에 scope로 인한 불필요한 코드리뷰 받으실까봐 미리 말씀드립니다!

참고로 전 기존 코드를 사용할 것 같습니다!

2024-08-29 04:36 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
> +        finish()
p1 : 여기서 image url을 넘길 필요는 없어보여요!
```suggestion
        setResult(Activity.RESULT_OK, Intent())
        finish()
```

2024-08-29 06:15 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/signup/SetProfileActivity.kt
> +        finish()
오 네엡-! 감사합니당 👍

2024-08-29 06:17 UTC, merged