[Fix/#192] 4차 QA
OMZigak/KKUM_ANDROID pull request #198
Opened 2024-09-22 06:34 UTC by hyoeunjoo

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #192 

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [x] 버튼 공통 component로 빼기
- [x] 모임 상세화면에서 탭바 눌려있는 상태 유지하기
- [x] 마이페이지 스크롤바
- [x] 바텀네비 아이콘과 글씨 간격 줄이기
- [x] 엠티뷰 캐릭터 수정

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/c72aec25-1665-437c-bcb5-c65c9fa298b6

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀

2024-09-22 07:11 UTC, chanubc requested changes
어려웠을 텐데 고생 많으셨습니다!
잘하셨네요~~~

2024-09-22 07:11 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailViewModel.kt
> +    var isMeetUpIncludeMeSelected: Boolean = true
p1 : 직접적으로 외부에서 수정 가능하게 하는것보다 getter setter를 사용하거나 mutablestateflow를 사용해서 옵저빙하는 쪽이 더 적합 할 것 같아요

ViewModel에서 관리하는 상태가 의도치 않게 변경되지 않도록 방지할 수 있고, 상태 변화를 옵저빙하여 UI를 자동으로 업데이트할 수 있는 장점이 있을것 같네요!

2024-09-22 07:11 UTC, chanubc commented on feature/src/main/res/layout/fragment_my_page.xml
> +        <ScrollView
p2 : scrollview보단 nested scroll view사용해주세요!

2024-09-22 07:11 UTC, chanubc commented on feature/src/main/res/layout/fragment_my_page.xml
> +            app:layout_constraintBottom_toBottomOf="parent"
p1 : 스크롤뷰의 marginbottom을 준 이유가 있을까요?

2024-09-22 07:11 UTC, chanubc commented on feature/src/main/res/layout/fragment_my_page.xml
> +                    app:title="@{@string/my_page_title}" />
p1 : app bar는 스크롤이 안되도록 해주세요! scroll view외부로 빼면 될거에요!

2024-09-22 07:11 UTC, chanubc commented on feature/src/main/res/values/themes.xml
> +
짱이에요!
혹시 여기서 consraint dimension ratio도 적용 할 수 있나요??

2024-09-22 10:29 UTC, hyoeunjoo commented on feature/src/main/res/values/themes.xml
> +
앗 아뇨ㅠㅠ 저도 그렇게 하려고 했는데 그건 Constraint에서 제공하는 부분이라서 따로 style에 정의할 수는 없더라구요

2024-09-22 10:29 UTC, hyoeunjoo commented on feature/src/main/res/layout/fragment_my_page.xml
> +                    app:title="@{@string/my_page_title}" />
맞네요..! 역시 디테일함! 감사합니다

2024-09-22 10:30 UTC, hyoeunjoo commented on feature/src/main/res/layout/fragment_my_page.xml
> +            app:layout_constraintBottom_toBottomOf="parent"
음.. 제가 구상하던 모습이 있는데요 굳이 스크롤뷰에다가 안해도 될 것 같습니다. 그게 더 나은 방법 같아요. 감사해요ㅎㅎㅎ

2024-09-23 06:07 UTC, chanubc approved these changes
톡으로 남겼던 문제 원인 파악 됬나요?
p1사항만 수정해주세요~

2024-09-23 06:07 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        if (viewModel.isMeetUpIncludeMeSelected.value) {
p1 : 여기 flow수집해서 옵저빙 해주세요!

2024-09-23 06:07 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailViewModel.kt
> +        _isMeetUpIncludeMeSelected.value = isSelected
kotlin 의 update함수도 사용이 가능합니다!
알아 두시면 좋아요~

2024-09-23 09:15 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        if (viewModel.isMeetUpIncludeMeSelected.value) {
넵! 아 이걸 깜빡했네요

원인은.. 정확하게는 못찾았습니다... 그래서 일단 원래 코드로 작성하긴 했는데요.
단지 delay로 제어권을 주었을때 약간의 깜빡임과 함께 원래 '내모임'버튼이 눌려져있다가 viewModel에 업데이트 된 값으로 ui 가 재구성되는 것으로 보아 ui에 반영되기까지의 시간이 부족했던 것 같습니다..

2024-09-23 09:17 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailViewModel.kt
> +        _isMeetUpIncludeMeSelected.value = isSelected
`
fun updateMeetUpIncludeMeState(isSelected: Boolean) {
    _isMeetUpIncludeMeSelected.update { isSelected }
}
`
이렇게 쓰면 될까요!!

2024-09-23 14:43 UTC, chanubc commented on feature/src/main/res/layout/fragment_my_page.xml
> +            app:layout_constraintBottom_toBottomOf="parent"
앗 의도 된거라면 괜찮습니다!

2024-09-23 14:44 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailViewModel.kt
> +        _isMeetUpIncludeMeSelected.value = isSelected
네네 그럼 좋습니다!

2024-09-23 14:49 UTC, chanubc approved these changes
12시전 코드리뷰 어푸어푸

2024-09-23 14:49 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
리뷰가 좀 늦었는데
```suggestion
        viewLifecycleScope.launch {
```

만들어 놓은 확장함수 있습니다!

2024-09-23 14:49 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +            viewModel.isMeetUpIncludeMeSelected.collect { isSelected ->
collect 보단 flowwithlifecylce, on Each 와 lanch in 사용해주세요~~
사실 싱글액티비티라 메모리 누수 면에서는 상관은 없긴한데 전체적으로 통일합시다!

추가로 collect와 collectlatest차이를 확인해보는 것도 좋습니다!
여기선 전 아마 collectlatest 쓸것 같아요!
최신 정보를 보여줘야 하는 페이지, UI를 구성할때는 여러 발행된 값중 결국 최종값만 받으면 된다 생각하거든요!

http://kotlinworld.com/252

2024-09-23 14:54 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +        viewLifecycleOwner.lifecycleScope.launch {
아......;....맞다..

2024-09-23 15:02 UTC, hyoeunjoo commented on feature/src/main/java/com/teamkkumul/feature/mygroup/mygroupdetail/MyGroupDetailFragment.kt
> +            viewModel.isMeetUpIncludeMeSelected.collect { isSelected ->
좋은 자료 주셔서 항상 감사합니다!!!

2024-09-23 15:03 UTC, chanubc reviewed
어푸어푸

2024-09-23 15:03 UTC, merged