[FEAT/#48] Splash Activity 구현
OMZigak/KKUM_ANDROID pull request #49
Opened 2024-07-14 08:03 UTC by yskim6772

## ✅ 𝗖𝗵𝗲𝗰𝗸-𝗟𝗶𝘀𝘁
- merge할 브랜치의 위치를 확인해 주세요(main❌/develop⭕)
- 리뷰가 필요한 경우 리뷰어를 지정해 주세요
- 리뷰는 (아직 미정)에 진행됩니다.
- P1 단계의 리뷰는 (아직 미정)까지 반영합니다.
- Approve된 PR은 assigner가 머지하고, 수정 요청이 온 경우 수정 후 다시 push를 합니다.

## 📌 𝗜𝘀𝘀𝘂𝗲𝘀
- closed #48

## 📎𝗪𝗼𝗿𝗸 𝗗𝗲𝘀𝗰𝗿𝗶𝗽𝘁𝗶𝗼𝗻
- [ ] Splash Activity 화면 구현
- [ ] SetNameActivity, MainActivity에서 빈 화면 클릭 시 키보드 내려가기 구현

## 📷 𝗦𝗰𝗿𝗲𝗲𝗻𝘀𝗵𝗼𝘁

https://github.com/user-attachments/assets/d369b20e-eff2-47e2-bab6-12f827acc930

## 💬 𝗧𝗼 𝗥𝗲𝘃𝗶𝗲𝘄𝗲𝗿𝘀
스플래시 화면의 시간은 1초로 구현했습니다 !

2024-07-14 16:23 UTC, chanubc requested changes
나날히 발전하는 모습 좋습니다!

p1사항들 수정해주세요~

2024-07-14 16:23 UTC, chanubc commented on app/build.gradle.kts
> +    id("androidx.navigation.safeargs.kotlin")
p1 : 버전 카탈로그를 통해서 관리해주세요

2024-07-14 16:23 UTC, chanubc commented on build.gradle.kts
> +}
p1 : 이 부분 지워주세요! 버전 카탈로그를 통한 라이브러리 관리를 해야 합니다!

2024-07-14 16:23 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/MainActivity.kt
> +    }
P1 : ui모델에서 open key board라는 확장함수 만들어 놓았습니다! 해당 함수 사용해보시고 적용 안되면 이 함수 쓰면 좋을것 같아요

2024-07-14 16:23 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/signup/SetNameActivity.kt
> +
p1 : 반복되는 함수들은 util로 따로 빼서 사용하는 것이 좋습니다.

2024-07-14 16:23 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/splash/SplashActivity.kt
> +    }
p1 : activity scope를 사용하신 이유가 있나요?
activity scope는 비동기 작업이 끝날때 까지 액티비티가 메모리에서 해지 되지 않을 가능 성이 있습니다.

activity scope가 아닌

```kotlin
 lifecycleScope.launch
```
라이프 사이클 스코프를 사용해 주세요!

2024-07-14 16:23 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/splash/SplashActivity.kt
> +    }
p1 :  lifecylcer scope를 사용한다면 cancle할 필요가 없어집니다.

2024-07-14 17:37 UTC, yskim6772 commented on feature/src/main/java/com/teamkkumul/feature/MainActivity.kt
> +    }
확장함수 적용 완료했습니다-!

2024-07-15 10:14 UTC, chanubc requested changes

2024-07-15 10:14 UTC, chanubc commented on feature/src/main/java/com/teamkkumul/feature/MainActivity.kt
> +    }
p1 : 적용 되면 이 코드는 삭제해주세요!

2024-07-15 10:16 UTC, chanubc approved these changes
머지 하셔도 좋습니다!

2024-07-15 10:18 UTC, merged